### ISSUE TITLE
Динамическая адресация подразделений и изменение реквизитов у заблокированного объекта (мой вариант)

### ISSUE THREAD

**Issue by Tambu** [BlizD/BPS#27]
[BPS инструкция.docx](https://github.com/BlizD/BPS/files/7668310/BPS.docx
[BPS.zip](https://github.com/BlizD/BPS/files/7668315/BPS.zip)
)
Добрый день! Во вложении мой вариант реализации.

**Comment by BlizD** [comment]
Спасибо, добавил в вики.
[Инструкция](https://github.com/BlizD/BPS/wiki/Динамическая-адресация-по-подразделениям)
[Инструкция](https://github.com/BlizD/BPS/wiki/Список-разрешенных-реквизитов-для-заблокированных-объектов-БД)

**Comment by BlizD** [comment]
Выпустил релиз 
![image](https://user-images.githubusercontent.com/10989306/145706264-92a7257b-b94f-4109-bc4f-21d1f46fca6f.png)
