### ISSUE TITLE
Произвольный алгоритм нахождения согласователей

### ISSUE THREAD

**Issue by Tambu** [BlizD/BPS#31]
[bps_ans.zip](https://github.com/BlizD/BPS/files/8002540/bps_ans.zip)
[БПС алгоритмы нахождения согласователей.docx](https://github.com/BlizD/BPS/files/8002542/default.docx)
Во вложенных файлах описание и вариант реализации.

**Comment by BlizD** [comment]
Залил вроде это уже в основную поставку и выпустил релиз
