### ISSUE TITLE
Ошибка в получении номера строки бпсОбщийМодуль строка 88 релиз .18

### ISSUE THREAD

**Issue by Poirus9** [BlizD/BPS#32]
Модуль бпсОбщийМодуль, строка 88.
https://github.com/BlizD/BPS/blob/5a7cc9a5d74741c55d6956d6e7dcd4e1206699ad/src/cf/CommonModules/%D0%B1%D0%BF%D1%81%D0%9E%D0%B1%D1%89%D0%B8%D0%B9%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C/Ext/Module.bsl#L88-L90
Нумерация строк в ТЧ начинается с 0, при таком подходе получаем ошибку, т.к. увеличение номера строки производится в начале, а не в конце

Пока НомСтроки < Источник[ТЧ.Имя].Количество() Цикл
// +удалить
     НомСтроки = НомСтроки+1;
//-удалить
     СтрокаТЧИсточник = Источник[ТЧ.Имя][НомСтроки];
     СтрокаТЧИсточникСсылка = Источник.Ссылка[ТЧ.Имя][НомСтроки];
//+добавить
     НомСтроки = НомСтроки+1;
//-добавить

**Comment by BlizD** [comment]
Спасибо, посмотрю

**Comment by BlizD** [comment]
Спасибо. Залил изменения.
