### ISSUE TITLE
В Согласование добавлена колонка "Согласователь" и "Алгоритм" на тч ЛистСогласования

### ISSUE THREAD

**Issue by YUYA1964** [BlizD/BPS#35]
Вывел в Лист согласования формы ФормаБизнесПроцесса колонки Согласователь и Алгоритм, т.к. при наличии согласования по алгоритму была просто пустая строка.

**Comment by BlizD** [comment]
@YUYA1964 Спасибо, Залил изменения.
Последний CF из дев ветки можно взять тут https://github.com/BlizD/BPS/issues/29
