### ISSUE TITLE
Добрый день! При настройки отправки сообщений(делала все как у вас на видео) при проверки выдает ошибку.

### ISSUE THREAD

**Issue by IrinaSuhih** [BlizD/BPS#6]
Добрый день! При настройки отправки сообщений(делала все как у вас на видео) при проверки выдает ошибку.
{ОбщийМодуль.бпсОбщийМодуль.Модуль(700)}: {ОбщийМодуль.бпсОбщийМодуль.Модуль(696)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (CDO.Message.1): Транспорту не удалось подключиться к серверу.

**Comment by BlizD** [comment]
Добрый день, Ирина.

Попробуйте сначала на общедоступном ящике (допустим на mail.ru).

![image](https://cloud.githubusercontent.com/assets/10989306/25692770/a49e36ce-30ad-11e7-8b3d-604b678dbb81.png)

Сначала с включенной галкой "Использовать типовые средства 1с при отправке почты" попробуйте отправить тестовое сообщение.
Если выдает ошибку, тогда с выключенной и опять попробуйте отправить сообщение.
Перед отправкой тестового сообщения обязательно необходимо нажимать записать в учетных записях.

**Comment by BlizD** [comment]
Если у Вас есть системный администратор, то лучше вместе с ним настраивать.
Обращаю внимание на галочку "Расширенные настройки", возможно там еще придется указать доп. сведения.

**Comment by IrinaSuhih** [comment]
Системный администратор говорит что порты открыты, и он сделал все что смог, поэтому обратилась к Вам. Из 1с уходит все корректно

**Comment by BlizD** [comment]
Ирина, 

попробуйте включить галку "Использовать типовые средства 1с при отправке почты".
Далее записать элемент учетной записи.
И попробуйте отправить тестовое сообщение 
![image](https://cloud.githubusercontent.com/assets/10989306/25699930/fee66802-30cd-11e7-9b8e-7ecb9f6e0d59.png)

Далее пришлите ошибку которая выдается.

**Comment by IrinaSuhih** [comment]
С выключенной галочкой 1с

С включенной настройкой 1с

**Comment by BlizD** [comment]
>С выключенной галочкой 1с
С включенной настройкой 1с

Ирина, возможно Вы указывали скриншоты, но их не видно.

**Comment by IrinaSuhih** [comment]
да верно там скриншоты!
с выключенной настройкой 1с 
{ОбщийМодуль.бпсОбщийМодуль.Модуль(700)}: {ОбщийМодуль.бпсОбщийМодуль.Модуль(696)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (CDO.Message.1): Транспорту не удалось подключиться к серверу.
ВызватьИсключение ОписаниеОшибки();
Не удалось отправить сообщение ОписаниеОшибки {ОбщийМодуль.бпсОбщийМодуль.Модуль(696)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (CDO.Message.1): Транспорту не удалось подключиться к серверу.
 с включенной настройкой 1с
{ОбщийМодуль.бпсОбщийМодуль.Модуль(861)}: Ошибка при вызове метода контекста (Послать)
Соединение.Послать(Письмо, ОбрабатыватьТекстСообщения);
по причине:
Сервис отключен с разрывом канала (SMTP error code 421 421 SMTP connection broken (reply))

**Comment by BlizD** [comment]
До этого из 1с у Вас письма отправлялись/получались?
Такое ощущение, что Брандмауэр прерывает канал или нет интернета.
Обращаю внимание, что отправка сообщения выполняется на стороне сервера под тем пользователям, под которым запущена служба 1с.
Надо проверить у этого пользователя есть доступ в интернет?

**Comment by BlizD** [comment]
Какой почтовый адрес указываете?
Ваш личный, который на mail.ru? или тот что используется на работе?
Есть ли у Вас почтовый сервер?

**Comment by BlizD** [comment]
О, Ирина.
Попробуйте настроить типовую учетную запись, эта та, что идет в вашей конфигурации.
![image](https://cloud.githubusercontent.com/assets/10989306/25701569/a3276eb4-30d5-11e7-899f-d8015a6043b3.png)
Укажите параметры тут:
![image](https://cloud.githubusercontent.com/assets/10989306/25701576/af3737d4-30d5-11e7-8029-a64613e0e520.png)
и нажмите "Проверить учетную запись"

**Comment by IrinaSuhih** [comment]
По порядку, да настроена отправка из 1С, все уходило, у пользователя интернет есть, почтовый сервер есть.

**Comment by BlizD** [comment]
Очень странно, просто те ошибки которые у Вас выдаются указывают на те места, на которые со стороны 1с повлиять не могу.
Можете прислать 2 скриншота: 
1) настройки из типовой учетной записи (по которой сейчас уже идет отправка писем из 1с)
2) настройки которые указали для учетной записи из согласования

Можете отправить на почту, если сюда не хотите выкладывать.

**Comment by BlizD** [comment]
Ирина, 
давайте попробуем пустить отправку сообщений по типовой учетной записи.

Для этого необходимо сделать следующее:
1) включить редактирование для модуля бпсОбщийМодуль
2) найти функцию ОтправитьСообщение
3) добавить вот этот код в эту функцию ОтправитьСообщение:

`	//+ Иванов А.Б. 2017-04-27 `
`	пУчетнаяЗапись = Справочники.УчетныеЗаписиЭлектроннойПочты.СистемнаяУчетнаяЗаписьЭлектроннойПочты; `
`	ИдентификаторСообщения = ЭлектроннаяПочта.ОтправитьСообщение(пУчетнаяЗапись,ПараметрыПисьма,Соединение);`
`	Возврат ИдентификаторСообщения;`
`	//- Иванов А.Б. 2017-04-27`
4) обновить конфигурацию

Как это сделать:
![changebps](https://cloud.githubusercontent.com/assets/10989306/25739163/67a60080-3189-11e7-8af8-ca304b6a9f08.gif)

**Comment by IrinaSuhih** [comment]
А настройки какие?

**Comment by BlizD** [comment]
> А настройки какие? 

можете оставить те что сейчас указаны.

**Comment by BlizD** [comment]
Задача разрешилась, пользователь вместе с сис. админом решили проблему
