### ISSUE TITLE
Ложное срабатывание проверки возможности использования, если реквизит не заполнен

### ISSUE THREAD

**Issue by leonvlas** [BlizD/BPS#9]
Если в документе (справочник не проверял, могу предположить что там тоже самое) есть реквизит с тем же типом, что и согласуемый документ.  То не возможно записать (создать)  документ даже если реквизит не заполнен.

выдается сообщение 
Ошибка! запрещено использовать объект [ ] , пока он не согласован для предмета согласования [документ]

как пример 
есть заявка. в котором есть реквизит "корректируемый документ" с тем же типом.
естественно этот реквизит не всегда заполняется.
при попытке записать новый документ выдается сообщение и документ не записывается.

**Comment by BlizD** [comment]
Добрый день. 

Странно, что так происходит. 
Есть ли возможность скинуть пример ошибочный? Выгрузку в dt? Можно на пустой базе.

**Comment by leonvlas** [comment]
вот сделал
[1Cv8_тест.zip](https://github.com/BlizD/BPS/files/1535118/1Cv8_.zip)

**Comment by leonvlas** [comment]
при создании заявки сообщение об ошибки

**Comment by BlizD** [comment]
@leonvlas постараюсь на выходных глянуть, сейчас не получится посмотреть.

**Comment by BlizD** [comment]
@leonvlas 
Спасибо, за ошибку .
Исправил, смотрил релиз:
https://github.com/BlizD/BPS/releases/download/1.0.0.014/BPS_1.0.0.014.zip

**Comment by leonvlas** [comment]
ok
